---
title: "Weight of Fish"
author: "Cadence Gorden"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(leaps)
library(car)
```
```{r}
Fish<- read_csv(file="Fish.csv") 
```



# Predicting Fish Weight


## Perch
```{r}
Perch<-filter(Fish, Species=="Perch")
Perch<-select(Perch, -Species)
```


### Best Models
```{r}
regsubsets.out <-
    regsubsets(Weight ~ .,
             data = Perch,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```

### Best Two regressor model
```{r}
Perchmode<-lm(Weight~Height+Width,data=Perch)
summary.lm(Perchmode)
```
Through filtering out the perch fish and only using numerical variables, we determined 
the best subset is the height and width and the best 2 subset is also the height and width

## Bream

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements